# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# PHP 5.2 and 5.3 are only available on Precise
# Ref: https://docs.travis-ci.com/user/reference/trusty#PHP-images
matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise

# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 5.6.33
  # aliased to a recent 7.x version
  - 7.0
  - 7.1
  - 7.2
  # aliased to a recent HipHop Virtual Machine version
  - hhvm

# optionally specify a list of environments
# Example to test different RDBMS
env:
  - DB=mysql
  - DB=pgsql

# optionally set up exclusions and allowed failures in the matrix
matrix:
  exclude:
      # PDO driver for pgsql is unsupported by HHVM
      #  - Requries: 3rd party install for support
    - php: hhvm
      env: DB=pgsql
  allow_failures:
    - php: 5.2
    - php: 5.3
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: hhvm

# execute any number of scripts before the test run
# custom env's are available as variables
before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit_$DB.xml --coverage-text

## configure notifications (email, IRC, campfire etc)
#notifications:
#  irc: "irc.freenode.org#yourfavouriteroomfortravis"

